### PR TITLE
fix: undefined process after moving to webpack 5

### PR DESCRIPTION
**Pull request by ccheraa**
Restore `process` variable in the browser using a Webpack plugin when the browser IDE is built in development mode.

### CODE REVIEW

**Review by duncdrum — COMMENTED** [review]
This is my local system using electron identical with chrome:
Screenshot 2021-08-10 at 15 58 12

**Comment by ccheraa** [comment]
I'm hoping https://github.com/eclipse-theia/theia/pull/9818 gets merged so we can avoid fixing this using workarounds.

**Comment by ccheraa** [comment]
fixed in eclipse-theia/theia#9972 for v1.17.0
Once we upgrade to Theia 1.17.0 we should roll-back this PR

**Comment by duncdrum** [comment]
> fixed in [eclipse-theia/theia#9972](https://github.com/eclipse-theia/theia/pull/9972) for v1.17.0
> Once we upgrade to Theia 1.17.0 we should roll-back this PR

please open an issue, as this comment will be hard to find once we merge this PR

**Pull request closed without merging**
