### PR TITLE
[BugFix] allow remote access access

### PR DESCRIPTION
**Pull request by marmoure**
according to thiea docs you need to specify the host name in the run script
[Thiea Docs](https://theia-ide.org/docs/composing_applications/) check **Running**

### CODE REVIEW

**Comment by duncdrum** [comment]
i m not sure what problem this is trying to solve. 

```shell
yarn start
```

works fine for me locally and on CI, do you have a problem bringing up the theia dev server?


>You **can** provide […] `--hostname`,` --port` options to deploy the application on specific network interfaces and ports

can != must
[docs](https://theia-ide.org/docs/composing_applications#running)

**Comment by marmoure** [comment]
The dev server works fine bht its binded to the localhost do we want it to say like that

**Comment by adamretter** [comment]
I think rather than code `0.0.0.0` into the script - is there a way we can pass the arg from the command line?

e.g. yarn start --hostname=

**Comment by marmoure** [comment]
Yes args works fine i m using them right now

**Comment by adamretter** [comment]
So if the args work do we need to add them to package.json at all?

**Comment by marmoure** [comment]
I thought we needed something permanent

**Comment by adamretter** [comment]
so does `yarn start --hostname=0.0.0.0` work?

**Comment by marmoure** [comment]
Yes

**Comment by adamretter** [comment]
Ah okay, then I am not sure we should set the default to binding to all addresses as that could be perceived as a security issue.

**Comment by marmoure** [comment]
Yes i closed the PR and i ll delete the branch

**Comment by marmoure** [comment]
We just need to update the Readme file

**Pull request closed without merging**
