### PR TITLE
added mocha for unit tests

### PR DESCRIPTION
**Pull request by ccheraa**

### CODE REVIEW

**Comment by duncdrum** [comment]
see #402

**Comment by duncdrum** [comment]
opps merged to quickly, @ccheraa can you hook up the unit tests into the default `yarn test` command of the build, thx

**Comment by ccheraa** [comment]
Yes, I waited on doing so because I wanted to make sure I can use a config file instead of command line arguments, and then forgot to add it.
I'll add it in my next PR.

**Comment by ccheraa** [comment]
It turns out it's not running correctly yet #407

**Pull request merged**
