### PR TITLE
Yarn should be installed via NPM - correct the README.md

### PR DESCRIPTION
**Pull request by adamretter**
Small fix to the README.md

### CODE REVIEW

**Comment by ccheraa** [comment]
From [Yarn website](https://classic.yarnpkg.com/en/docs/install/#alternatives-stable):

> Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.
For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

So I think it's better to leave the decision for the user, because the download page provides all possible options including NPM.

**Comment by adamretter** [comment]
@ccheraa Good point! I reworded the text to make it more of a suggestion and I linked to the implication. Do you think it is okay now?

**Comment by ccheraa** [comment]
Yes, this looks good. 👍

**Comment by adamretter** [comment]
@ccheraa Okay, can you merge?

**Pull request merged**
